### ISSUE TITLE
Incorrect/bad dimensionality recommendation

### ISSUE THREAD

**Issue by sapoudel** [SBRG/pymodulon#44]
The notebook sometimes recommends incorrect/bad dimensionality. In some cases, it will recommend high dimensionality even when the number of robust components drop sharply (see image). In these high dimensional decomposition (almost) all iModulons have near 0 activities in all samples.  

![image](https://user-images.githubusercontent.com/30187316/100493864-6b92d000-30f0-11eb-917e-5cf95ee12843.png)

**Comment by avsastry** [comment]
This is fixed in the modulome-workflow version here: https://github.com/avsastry/modulome-workflow/tree/main/4_optICA
The dimensionality search is integrated in with the rest of the code as well.
