### ISSUE TITLE
IcaData iModulon Table is not properly set

### ISSUE THREAD

**Issue by siddC** [SBRG/pymodulon#74]
In notebook 5a, I generate a partial iModulon Table (only characterized known TRN iModulons and single_gene iModulons). In a seperate notebook I try to load that iModulon Table into my IcaData object but it:

1. gives me a warning that some iModulon values are missing (namely just numbers that have been characterized and now have names like `FadR`)
2. does not actually fill in the iModulon table with the proper values (see below)

![Screen Shot 2021-04-10 at 11 23 53 AM](https://user-images.githubusercontent.com/11781272/114280665-3d52c480-99ef-11eb-8727-37f0544de9a9.png)

**Comment by avsastry** [comment]
I think you need to re-name the iModulons first. When you initialize the ica_data object, it will use the iModulon names from the M matrix (which is just numbers by default). You're then trying to load an iModulon table with different names. You can fix this with one of two options:
1) Rename the iModulons before loading the iModulon table (`ica_data.rename_imodulons`)
2) Add a new first column to your iModulon table that goes from 1 to # iModulons. Then you can load the `imodulon_table` in the initialization of the `IcaData` object. After that you can use `ica_data.imodulon_names = ica_data.imodulon_table[<name of iModulon name column>]`

If either of these work, please let me know.
